# The URL the site will be built for
base_url = "https://phel-lang.org"

title = "The Phel Language"
description = "The official website of the Phel language. Phel is a functional programming language that compiles to PHP"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[search]
# Include page content in the search index
include_title = true
include_description = true
include_path = false
include_content = true
# Include more content to make search more comprehensive
truncate_content_length = 5000

generate_feeds = false

[markdown.highlighting]
theme = "github-dark"
extra_grammars = ["syntaxes/phel.tmLanguage.json"]

[extra]
# Put all your custom variables here

repo_content_url = "https://github.com/phel-lang/phel-lang.org/edit/master/content/"
phel_version = "v0.29.0"
